import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import Header from "../components/navBar/landingHeader";
export default function Home() {
  const { locale, locales, asPath } = useRouter();
<<<<<<< HEAD
  const {data:session} = useSession()
  console.log(session)
=======

  const t = locale === 0 ? en : ar;



>>>>>>> 2b40437e24f871855c40fa1784b54632fa41e319
  return (
    <>
      <Header />
      <div className={styles.container}>
        <Head>
          <title>Hello World</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <center>Hello World</center>
      </div>
    </>
  );
}
